players can build: false
name: Island Tower
creator: DrMogga
description: downloaded from https://www.planetminecraft.com/ project/small-lobby-fantasy-waiting-lobby/
icon: heart_of_the_sea
center:
  x: 0
  y: 142
  z: 0
use border: true
border radius: 70
spawn radius: 17
spawn center:
  x: 0
  y: 142
  z: 0

