auto-update: true
maps directory: BGHR_Maps/
loaded maps directory: loaded_maps/
show main scoreboard: true
main world:
  place players at spawn on join: false
  kits useable in main world: true
  gamemode: adventure
always-on games: [ ]
games that will not start randomly: [ horizon_city ]
allow FreeForAll games to start randomly: false
keep at least this many games running: 1
use mysql instead of h2: false
mysql:
  hostname: localhost
  port: 3306
  database: bghr
  user: minecraft
  pass: hunter2
  arguments: ''
