maps directory: BGHR_Maps/
reset main world on each restart: false
lobby world to copy: BGHR_Maps/islandtower
loaded maps directory: loaded_maps/
main world:
  players can build normally: false
  place players at spawn on join: true
  kits useable in main world: true