name: unnamed map
creator: unknown
description: This map was added to the maps directory but hasn't been set up yet
icon: grass_block
use border: true
border radius: 100
border center:
  x: 0
  y: 80
  z: 0
spawn center:
  x: -102
  y: 76
  z: -45
spawn radius: 10
