name: BattleGamesHungerRoyale
main: me.cheracc.battlegameshungerroyale.BGHR
version: ${project.version}
api-version: 1.16
load: STARTUP
softdepend: [Vault]
commands:
  savemap:
    usage: "/savemap"
    description: "saves the current map"
  mapconfig:
    usage: "/mapconfig"
    description: "opens a gui to modify a map's configuration"
    permission: bghr.admin.maps
  kit:
    usage: "/kit <kit>"
    description: "equip yourself with the chosen kit"
  kitmenu:
    usage: "/kitmenu"
    description: "shows a menu of available kits"
  kitconfig:
    usage: "/kitconfig"
    description: "opens a gui to configure a kit"
    permission: bghr.admin.kits
  games:
    usage: "/games"
    description: "shows currently active games to join or spectate"
  quit:
    usage: "/quit"
    description: "leaves a game and returns to the lobby world"
  bghr:
    usage: "/bghr"
    description: "opens the BGHR admin menu"
    permission: bghr.admin.menu
  settings:
    usage: "/settings"
    description: "opens player settings menu"