name: King of the Ring
creator: X_SooN_x (Discord:DelusionMc)
description: A very small example map for up to 8 players. Players start on a central
  floating platform with lots of loot to find!
icon: red_mushroom_block
center:
  x: -102
  y: 76
  z: -45
use border: true
border radius: 50
border center:
  x: -102
  y: 76
  z: -45
spawn center:
  x: -102
  y: 76
  z: -45
spawn radius: 7
